import * as sqldb from '../connectSql'

/* @IFHELPER:FUNC getCommandsList = SELECT

  FROM CHILLER_CARRIER_30HXE_GXE_COMMANDS

  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.COMMAND,
  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.SYS_ID,
  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.ADDRESS,
  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.DESCRIPTION,
  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.IP,
  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.ID,
  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.SIZE,
  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.FUNC_ID,
  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.R_W,
  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.UNIT,
  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.FORMULA,
  SELECT CHILLER_CARRIER_30HXE_GXE_COMMANDS.ALIAS
*/
export function getCommandsList (qPars: {
}) {
  let sentence = `
    SELECT
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.COMMAND,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.SYS_ID,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.ADDRESS,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.DESCRIPTION,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.IP,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.ID,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.SIZE,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.FUNC_ID,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.R_W,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.UNIT,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.FORMULA,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.ALIAS,
    CHILLER_CARRIER_30HXE_GXE_COMMANDS.HAS_SIGNAL
  `

  sentence += `
    FROM
      CHILLER_CARRIER_30HXE_GXE_COMMANDS
    ORDER BY CAST(SUBSTRING(COMMAND, 4, 3) AS UNSIGNED)
  `

  return sqldb.query<{
    COMMAND: string
    SYS_ID: number
    ADDRESS: number
    DESCRIPTION: string
    IP: string
    ID: number
    SIZE: number
    FUNC_ID: number
    R_W: string
    UNIT: string
    FORMULA: string
    ALIAS: string
    HAS_SIGNAL: string
  }>(sentence, qPars)
}