import * as sqldb from '../connectSql'

export function getBasicInfo (qPars: { devId: string }) {
  let sentence = `
      SELECT
        DEVICES.DEVICE_CODE AS DEV_ID,
        DEVICES.ID AS DEVICE_ID,
        DEVICES_CLIENTS.CLIENT_ID,
        DEVICES_CLIENTS.ID AS DEVICE_CLIENT_ID,
        DEVICES_UNITS.UNIT_ID,
        DEVICES_UNITS.ID AS DEVICE_UNIT_ID,
        CASE WHEN DACS_DEVICES.ID IS NOT NULL THEN DEVICES.DEVICE_CODE END AS DAC_ID,
        CASE WHEN DAMS_DEVICES.ID IS NOT NULL THEN DEVICES.DEVICE_CODE END AS DAM_ID,
        CASE WHEN DUTS_DEVICES.ID IS NOT NULL THEN DEVICES.DEVICE_CODE END AS DUT_ID
  `
  sentence += `
    FROM
      DEVICES
      LEFT JOIN DUTS_DEVICES ON (DUTS_DEVICES.DEVICE_ID = DEVICES.ID)
      LEFT JOIN DEVICES_UNITS ON (DEVICES_UNITS.DEVICE_ID = DEVICES.ID)
      LEFT JOIN DEVICES_CLIENTS ON (DEVICES_CLIENTS.DEVICE_ID = DEVICES.ID)
      LEFT JOIN DACS_DEVICES ON (DACS_DEVICES.DEVICE_ID = DEVICES.ID)
      LEFT JOIN DAMS_DEVICES ON (DAMS_DEVICES.DEVICE_ID = DEVICES.ID)
  `

  sentence += ` WHERE DEVICES.DEVICE_CODE = :devId `

  return sqldb.querySingle<{
    DEV_ID: string
    DEVICE_ID: number
    CLIENT_ID: number
    DEVICE_CLIENT_ID: number
    UNIT_ID: number
    DEVICE_UNIT_ID: number
    DAC_ID: string
    DAM_ID: string
    DUT_ID: string
  }>(sentence, qPars)
}
