import * as sqldb from '../connectSql'

/* @IFHELPER:FUNC getCommandsList = SELECT

  FROM SCHNEIDER_PM2100_COMMANDS

  SELECT SCHNEIDER_PM2100_COMMANDS.COMMAND,
  SELECT SCHNEIDER_PM2100_COMMANDS.SYS_ID,
  SELECT SCHNEIDER_PM2100_COMMANDS.ADDRESS,
  SELECT SCHNEIDER_PM2100_COMMANDS.DESCRIPTION,
  SELECT SCHNEIDER_PM2100_COMMANDS.IP,
  SELECT SCHNEIDER_PM2100_COMMANDS.ID,
  SELECT SCHNEIDER_PM2100_COMMANDS.SIZE,
  SELECT SCHNEIDER_PM2100_COMMANDS.FUNC_ID,
  SELECT SCHNEIDER_PM2100_COMMANDS.R_W,
  SELECT SCHNEIDER_PM2100_COMMANDS.UNIT,
  SELECT SCHNEIDER_PM2100_COMMANDS.FORMULA,
  SELECT SCHNEIDER_PM2100_COMMANDS.ALIAS
*/
export function getCommandsList (qPars: {
}) {
  let sentence = `
    SELECT
    SCHNEIDER_PM2100_COMMANDS.COMMAND,
    SCHNEIDER_PM2100_COMMANDS.SYS_ID,
    SCHNEIDER_PM2100_COMMANDS.ADDRESS,
    SCHNEIDER_PM2100_COMMANDS.DESCRIPTION,
    SCHNEIDER_PM2100_COMMANDS.IP,
    SCHNEIDER_PM2100_COMMANDS.ID,
    SCHNEIDER_PM2100_COMMANDS.SIZE,
    SCHNEIDER_PM2100_COMMANDS.FUNC_ID,
    SCHNEIDER_PM2100_COMMANDS.R_W,
    SCHNEIDER_PM2100_COMMANDS.UNIT,
    SCHNEIDER_PM2100_COMMANDS.FORMULA,
    SCHNEIDER_PM2100_COMMANDS.ALIAS
  `

  sentence += `
    FROM
      SCHNEIDER_PM2100_COMMANDS
    ORDER BY CAST(SUBSTRING(COMMAND, 4, 3) AS UNSIGNED)
  `

  return sqldb.query<{
    COMMAND: string
    SYS_ID: number
    ADDRESS: number
    DESCRIPTION: string
    IP: string
    ID: number
    SIZE: number
    FUNC_ID: number
    R_W: string
    UNIT: string
    FORMULA: string
    ALIAS: string
  }>(sentence, qPars)
}
