apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-server
  title: API-Server
  annotations:
    github.com/project-slug: dielenergia/API-Server
    github.com/project-repo: dielenergia/API-Server
    sonarqube.org/project-key: dielenergia_API-Server_AYFKvKQeX-Ga31iuycAD
  tags:
    - typescript
    - backend
spec:
  type: service
  system: dap
  lifecycle: production
  owner: software
  dependsOn:
    - resource:mysql
  consumesApis:
    - fdd-api
  providesApis:
    - api-server-api
