
import { faker } from '@faker-js/faker';
import sqldb from "../../../srcCommon/db";
import { ControlMode } from '../../../srcCommon/types';

interface DevFullInfo {
    DEV_ID: string
    DEVICE_ID: number
    BT_ID: string
    UNIT_ID: number
    CLIENT_ID: number
    DAT_BEGMON: string
    LTE_NETWORK: string
    LTE_RSRP: number
    UNIT_NAME: string
    CITY_ID: string
    TIMEZONE_ID: number
    TIMEZONE_AREA: string
    TIMEZONE_OFFSET: number
    STATE_ID: string
    CITY_NAME: string
    CLIENT_NAME: string
    CURRFW_MSG: string
    CURRFW_VERS: string
    HAS_DUT_AUT: string
    DAT_BEGAUT_DUT_AUT: string
    DESIREDPROG_DUT: string
    LASTPROG_DUT: string  
    DUTAUT_DISABLED: number
    DUTAUT_MCHN_BRAND: string
    DUTAUT_MCHN_MODEL: string
    TSETPOINT_DUT: number
    LTCRIT_DUT: number
    RESENDPER_DUT: number
    FU_NOM_DUTAUT: number
    DUTAUT_CTRLOPER: ControlMode
    DUTAUT_PORTCFG: 'IR'|'RELAY'
    LTINF_DUT: number
    DUT_UPPER_HYSTERESIS: number
    DUT_LOWER_HYSTERESIS: number
    SELF_REFERENCE: number
    MINIMUM_TEMPERATURE: number
    MAXIMUM_TEMPERATURE: number
    EXT_THERM_CFG: string
    SETPOINT_ECO_REAL_TIME: number
    CAN_SELF_REFERENCE: number
    DUT_SCHEDULE_START_BEHAVIOR: string
    DUT_SCHEDULE_END_BEHAVIOR: string
    DUT_FORCED_BEHAVIOR: string
    HAS_DUT: string
    ENVIRONMENT_ID: number
    ROOM_NAME: string
    RTYPE_ID: number
    PLACEMENT: 'AMB'|'INS'|'DUO'
    VARS_DUT: string
    TEMPERATURE_OFFSET: number
    SENSOR_AUTOM: number
    TUSEMIN: number
    TUSEMAX: number
    HUMIMAX: number,
    HUMIMIN: number,
    USEPERIOD: string
    RTYPE_NAME: string
    CO2MAX: number
    HAS_DAM: string
    DAT_BEGAUT_DAM: string
    DESIREDPROG_DAM: string
    INSTALLATION_LOCATION_DAM: string
    LASTPROG_DAM: string
    FAULTSDATA_DAM: string
    ENABLE_ECO_DAM: 0|1|2
    ENABLE_ECO_LOCAL_DAM: 0|1
    FW_MODE: string
    ECO_CFG_DAM: string
    ECO_OFST_START_DAM: number
    ECO_OFST_END_DAM: number
    DAM_DISABLED: 0|1
    FU_NOM_DAM: number
    ECO_INT_TIME: number
    SCHEDULE_START_BEHAVIOR: string
    SETPOINT: number
    LTC: number
    LTI: number
    UPPER_HYSTERESIS: number
    LOWER_HYSTERESIS: number
    HAS_DAC: string
    DAC_NAME: string
    DAC_DESC: string
    DAC_MODEL: string
    CAPACITY_UNIT: string
    CAPACITY_PWR: number
    DAC_COP: number
    DAC_KW: number
    FLUID_TYPE: string
    GROUP_ID: number
    DAC_APPL: string
    DAC_TYPE: string
    DAC_ENV: string
    DAC_MODIF: string
    DAC_COMIS: string
    DAC_BRAND: string
    HEAT_EXCHANGER_ID: number
    SELECTED_L1_SIM: string
    GROUP_NAME: string
    REL_DUT_ID_GROUP: string
    FAULTSDATA_DAC: string
    P0_POSITN: string
    P0_SENSOR: string
    P1_POSITN: string
    P1_SENSOR: string
    P0_MULT_QUAD: number
    P0_MULT_LIN: number
    P0_OFST: number
    P1_MULT_QUAD: number
    P1_MULT_LIN: number
    P1_OFST: number
    T0_T1_T2: string
    APPLICATION: string
    HAS_DRI: string
    DAT_BEGAUT_DRI: string
    VARSCFG: string
    HAS_DMA: string
    DRI_GROUP: number
    EQUIPMENT_POWER: string
    COMPRESSOR_NOMINAL_CURRENT: number
    DAM_PLACEMENT: 'RETURN'|'DUO'
    T0_POSITION: 'RETURN'|'INSUFFLATION'
    T1_POSITION: 'RETURN'|'INSUFFLATION'
    ASSET_ID: number
}; 


export function generateDevExtraInfo(devId?: string): DevFullInfo {
    return {
        BT_ID: faker.string.alphanumeric(),
        DEVICE_ID: faker.number.int(),
        DEV_ID: devId || faker.string.alphanumeric(),
        CITY_ID: faker.number.int().toString(),
        CITY_NAME: faker.location.city(),
        CLIENT_ID: faker.number.int(),
        CLIENT_NAME: faker.company.name(),
        LTE_NETWORK: null,
        LTE_RSRP: null,
        DAC_APPL: null,
        DAC_TYPE: null,
        DAC_BRAND: null,
        DAC_COMIS: null,
        DAC_COP: null,
        DAC_DESC: null,
        DAC_ENV: null,
        DAC_KW: null,
        DAC_MODEL: null,
        DAC_MODIF: null,
        DAC_NAME: null,
        HAS_DAC: "",
        DAM_DISABLED: null,
        DAT_BEGAUT_DAM: null,
        DAT_BEGAUT_DRI: null,
        DAT_BEGAUT_DUT_AUT: null,
        DAT_BEGMON: null,
        CAN_SELF_REFERENCE: null,
        CAPACITY_UNIT: null,
        CAPACITY_PWR: null,
        CURRFW_VERS: faker.system.semver(),
        CURRFW_MSG: null,
        ECO_CFG_DAM: null,
        FAULTSDATA_DAC: null,
        FAULTSDATA_DAM: null,
        P0_MULT_LIN: null,
        P0_MULT_QUAD: null,
        P0_OFST: null,
        P0_POSITN: null,
        P0_SENSOR: null,
        P1_MULT_LIN: null,
        P1_MULT_QUAD: null,
        P1_OFST: null,
        P1_POSITN: null,
        P1_SENSOR: null,
        APPLICATION: null,
        PLACEMENT: faker.helpers.arrayElement(["AMB", "DUO"]),
        GROUP_ID: faker.number.int(),
        GROUP_NAME: faker.commerce.department(),
        DESIREDPROG_DAM: null,
        DESIREDPROG_DUT: null,
        DRI_GROUP: null,
        HAS_DRI: null,
        DUT_FORCED_BEHAVIOR: "",
        DUT_LOWER_HYSTERESIS: 0,
        DUT_UPPER_HYSTERESIS: 25,
        DUT_SCHEDULE_START_BEHAVIOR: null,
        DUT_SCHEDULE_END_BEHAVIOR: null,
        DUTAUT_CTRLOPER: null,
        DUTAUT_DISABLED: null,
        DUTAUT_MCHN_BRAND: null,
        DUTAUT_MCHN_MODEL: null,
        DUTAUT_PORTCFG: null,
        ECO_INT_TIME: null,
        ECO_OFST_END_DAM: null,
        ECO_OFST_START_DAM: null,
        ENABLE_ECO_DAM: null,
        ENABLE_ECO_LOCAL_DAM: null,
        ENVIRONMENT_ID: null,
        EXT_THERM_CFG: null,
        FU_NOM_DAM: null,
        FU_NOM_DUTAUT: null,
        FLUID_TYPE: null,
        HAS_DAM: null,
        HAS_DMA: null,
        HAS_DUT: null,
        HAS_DUT_AUT: null,
        FW_MODE: null,
        CO2MAX: null,
        HEAT_EXCHANGER_ID: null,
        LASTPROG_DAM: null,
        LASTPROG_DUT: null,
        LOWER_HYSTERESIS: null,
        LTC: null,
        LTCRIT_DUT: null,
        LTI: null,
        LTINF_DUT: null,
        MAXIMUM_TEMPERATURE: null,
        MINIMUM_TEMPERATURE: null,
        REL_DUT_ID_GROUP: null,
        RESENDPER_DUT: null,
        ROOM_NAME: null,
        RTYPE_ID: faker.number.int(),
        RTYPE_NAME: faker.commerce.department(),
        INSTALLATION_LOCATION_DAM: faker.commerce.department(),
        SCHEDULE_START_BEHAVIOR: null,
        SELECTED_L1_SIM: null,
        SELF_REFERENCE: null,
        SENSOR_AUTOM: null,
        SETPOINT: null,
        SETPOINT_ECO_REAL_TIME: null,
        STATE_ID: null,
        T0_T1_T2: null,
        TEMPERATURE_OFFSET: faker.number.float(),
        TIMEZONE_AREA: null,
        TIMEZONE_ID: null,
        TIMEZONE_OFFSET: null,
        TSETPOINT_DUT: null,
        TUSEMAX: null,
        TUSEMIN: null,
        HUMIMAX: null,
        HUMIMIN: null,
        UNIT_ID: null,
        UNIT_NAME: null,
        UPPER_HYSTERESIS: null,
        USEPERIOD: null,
        VARS_DUT: null,
        VARSCFG: null,
        EQUIPMENT_POWER: null,
        COMPRESSOR_NOMINAL_CURRENT: null,
        DAM_PLACEMENT: 'DUO',
        T0_POSITION: 'RETURN',
        T1_POSITION: 'INSUFFLATION',
        ASSET_ID: faker.number.int({ min: 1 }),
    }
}
