CREATE TABLE SCHNEIDER_PM210_COMMANDS (
  ADDRESS int unsigned NOT NULL,
  ALIAS varchar(30) DEFAULT NULL,
  COMMAND varchar(20) NOT NULL,
  DESCRIPTION varchar(50) NOT NULL,
  FORMULA varchar(35) DEFAULT NULL,
  FUNC_ID tinyint unsigned NOT NULL,
  ID tinyint unsigned NOT NULL,
  IP varchar(30) DEFAULT NULL,
  R_W varchar(3) NOT NULL,
  SIZE tinyint unsigned NOT NULL,
  SYS_ID tinyint unsigned NOT NULL,
  UNIT varchar(10) DEFAULT NULL,

  PRIMARY KEY (ADDRESS),
  CONSTRAINT SCHNEIDER_PM210_COMMANDS_uk_ALIAS UNIQUE KEY (ALIAS),
  CONSTRAINT SCHNEIDER_PM210_COMMANDS_uk_COMMAND UNIQUE KEY (COMMAND)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (999, 'en_at_tri', 'CMN0', 'Energia Ativa Total', NULL, 3, 0, NULL, 'R', 2, 0, 'kWh');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1001, 'en_ap_tri', 'CMN1', 'Energia Aparente Total ', NULL, 3, 0, NULL, 'R', 2, 0, 'kVAh');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1003, 'en_re_tri', 'CMN2', 'Energia Reativa Total ', NULL, 3, 0, NULL, 'R', 2, 0, 'kVArh');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1005, 'pot_at_tri', 'CMN3', 'Potência Ativa Trifásica', NULL, 3, 0, NULL, 'R', 2, 0, 'kW');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1007, 'pot_ap_tri', 'CMN4', 'Potência Aparente Trifásica', NULL, 3, 0, NULL, 'R', 2, 0, 'kVA');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1009, 'pot_re_tri', 'CMN5', 'Potência Reativa Trifásica', NULL, 3, 0, NULL, 'R', 2, 0, 'kVAr');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1011, 'fp', 'CMN6', 'Fator de Potência Total', NULL, 3, 0, NULL, 'R', 2, 0, NULL);
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1019, 'freq', 'CMN7', 'Frequência', NULL, 3, 0, NULL, 'R', 2, 0, 'Hz');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1021, 'demanda', 'CMN8', 'Demanda Presente Potência Ativa ', NULL, 3, 0, NULL, 'R', 2, 0, 'kW');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1027, NULL, 'CMN9', 'Demanda Pico Potência Ativa ', NULL, 3, 0, NULL, 'R', 2, 0, 'kW');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1033, 'i_a', 'CMN10', 'Corrente de Fase I1', NULL, 3, 0, NULL, 'R', 2, 0, 'A');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1035, 'i_b', 'CMN11', 'Corrente de Fase I2', NULL, 3, 0, NULL, 'R', 2, 0, 'A');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1037, 'i_c', 'CMN12', 'Corrente de Fase I3', NULL, 3, 0, NULL, 'R', 2, 0, 'A');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1059, 'v_a', 'CMN13', 'Tensão de Fase L1-N', NULL, 3, 0, NULL, 'R', 2, 0, 'V');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1061, 'v_b', 'CMN14', 'Tensão de Fase L2-N', NULL, 3, 0, NULL, 'R', 2, 0, 'V');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1063, 'v_c', 'CMN15', 'Tensão de Fase L3-N', NULL, 3, 0, NULL, 'R', 2, 0, 'V');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1053, 'v_ab', 'CMN16', 'Tensão de Linha L1-L2', NULL, 3, 0, NULL, 'R', 2, 0, 'V');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1055, 'v_bc', 'CMN17', 'Tensão de Linha L2-L3', NULL, 3, 0, NULL, 'R', 2, 0, 'V');
INSERT INTO SCHNEIDER_PM210_COMMANDS (ADDRESS, ALIAS, COMMAND, DESCRIPTION, FORMULA, FUNC_ID, ID, IP, R_W, SIZE, SYS_ID, UNIT) VALUES (1057, 'v_ca', 'CMN18', 'Tensão de Linha L3-L1', NULL, 3, 0, NULL, 'R', 2, 0, 'V');

INSERT INTO ENERGY_METER_MODELS (MANUFACTURER_ID, NAME) VALUES (3, 'Schneider PM210');

-- $$ --

RENAME TABLE ENERGY_ANALYSIS_MODELS TO ANALYSIS_MODELS, ENERGY_ANALYSIS_MODELS_FILTERS_VALUES TO ANALYSIS_MODELS_FILTERS_VALUES, ENERGY_ANALYSIS_MODELS_SHARED to ANALYSIS_MODELS_SHARED;

INSERT INTO ANALYSIS_MODELS (NAME, INTERESTS_ORGANIZATION, IS_HISTORIC) VALUES ('Maquinas', 'INTERESTS_ORGANIZATION', 0);
ALTER TABLE ANALYSIS_MODELS ADD IS_HISTORIC tinyint DEFAULT 1 NOT NULL;

ALTER TABLE CURRENT_DEVICE_STATE ADD TEMPERATURE decimal(3,1) NULL;
ALTER TABLE CURRENT_DEVICE_STATE ADD TEMPERATURE1 decimal(3,1) NULL;
ALTER TABLE CURRENT_DEVICE_STATE ADD STATE varchar(20) NULL;

-- $$ --

CREATE TABLE VAV_BAC_6000_AMLN_COMMANDS (
  ADDRESS tinyint(3) unsigned NOT NULL,
  ALIAS varchar(30) DEFAULT NULL,
  COMMAND varchar(20) NOT NULL,
  DESCRIPTION varchar(50) NOT NULL,
  FORMULA varchar(30) DEFAULT NULL,
  FUNC_ID tinyint(3) unsigned NOT NULL,
  ID tinyint(3) unsigned NOT NULL DEFAULT 1,
  IP varchar(30) DEFAULT NULL,
  R_W varchar(3) NOT NULL,
  SIZE tinyint(3) unsigned NOT NULL DEFAULT 1,
  SYS_ID tinyint(3) unsigned NOT NULL DEFAULT 1,
  UNIT varchar(10) DEFAULT NULL,

  PRIMARY KEY (ADDRESS,R_W),
  CONSTRAINT VAV_BAC_6000_AMLN_COMMANDS_uk_ALIAS UNIQUE KEY (ALIAS),
  CONSTRAINT VAV_BAC_6000_AMLN_COMMANDS_uk_COMMAND UNIQUE KEY (COMMAND)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


INSERT INTO VAV_BAC_6000_AMLN_COMMANDS (ADDRESS,ALIAS,COMMAND,DESCRIPTION,FORMULA,FUNC_ID,ID,IP,R_W,SIZE,SYS_ID,UNIT) VALUES
('0','therm-on','CMN0','Status do termostato',NULL,3,1,NULL,'R',1,1,NULL),
('0','set-therm','CMN17','Status do termostato',NULL,6,1,NULL,'W',1,1,NULL),
('1','fanspeed','CMN1','Velocidade de ventilação',NULL,3,1,NULL,'R',1,1,NULL),
('1','set-fanspeed','CMN18','Velocidade de ventilação',NULL,6,1,NULL,'W',1,1,NULL),
('2','set-mode','CMN19','Modo de operação',NULL,6,1,NULL,'W',1,1,NULL),
('2','mode','CMN2','Modo de operação',NULL,3,1,NULL,'R',1,1,NULL),
('3','set-setpoint','CMN20','Setpoint','*10',6,1,NULL,'W',1,1,'°C'),
('3','setpoint','CMN3','Setpoint','/10',3,1,NULL,'R',1,1,'°C'),
('4','set-lock','CMN21','Screen lock',NULL,6,1,NULL,'W',1,1,NULL),
('4','lock','CMN4','Screen lock',NULL,3,1,NULL,'R',1,1,NULL),
('5','set-minutes','CMN22','Minutos',NULL,6,1,NULL,'W',1,1,NULL),
('5','minutes','CMN5','Minutos',NULL,3,1,NULL,'R',1,1,'Min'),
('6','set-hours','CMN23','Horas',NULL,6,1,NULL,'W',1,1,NULL),
('6','hours','CMN6','Horas',NULL,3,1,NULL,'R',1,1,'H'),
('7','set-weekday','CMN24','Dia da semana',NULL,6,1,NULL,'W',1,1,NULL),
('7','weekday','CMN7','Dia da semana',NULL,3,1,NULL,'R',1,1,NULL),
('8','valve-type','CMN8','Tipo de válvula',NULL,3,1,NULL,'R',1,1,NULL),
('8','set-valve-type','CMN25','Tipo de válvula',NULL,6,1,NULL,'W',1,1,NULL),
('9','sensor-select','CMN9','Ler sensor interno ou externo',NULL,3,1,NULL,'R',1,1,NULL),
('9','set-sensor-select','CMN26','Ler sensor interno ou externo',NULL,6,1,NULL,'W',1,1,NULL),
('10','p-value','CMN10','P Value',NULL,3,1,NULL,'R',1,1,NULL),
('10','set-p-value','CMN27','P Value',NULL,6,1,NULL,'W',1,1,NULL),
('11','i-value','CMN11','I Value',NULL,3,1,NULL,'R',1,1,NULL),
('11','set-i-value','CMN28','I Value',NULL,6,1,NULL,'W',1,1,NULL),
('12','ext-temp','CMN12','Temp ambiente externa','/10',3,1,NULL,'R',1,1,'°C'),
('12','set-ext-temp','CMN29','Temp ambiente externa','*10',6,1,NULL,'W',1,1,'°C'),
('13','valve-cmd','CMN13','Sinal enviado ao atuador',NULL,3,1,NULL,'R',1,1,'%'),
('14','temp-amb','CMN14','Temp ambiente interna','/10',3,1,NULL,'R',1,1,'°C'),
('15','valve-on','CMN15','Status do atuador',NULL,3,1,NULL,'R',1,1,'%'),
('16','fan-status','CMN16','Status da ventilação',NULL,3,1,NULL,'R',1,1,NULL);

UPDATE VAV_BAC_COMMANDS SET DESCRIPTION = "Screen Lock" WHERE ADDRESS = 4;

-- $$ --

ALTER TABLE FANCOILS ADD VALVE_TYPE varchar(50) NULL;
ALTER TABLE VAVS ADD VALVE_TYPE varchar(50) NULL;

UPDATE FANCOILS SET VALVE_TYPE = "PROPORTIONAL" WHERE VALVE_TYPE IS NULL;
UPDATE VAVS SET VALVE_TYPE = "PROPORTIONAL" WHERE VALVE_TYPE IS NULL;

-- $$ --

ALTER TABLE DUTS_DUO_EVAPORATORS ADD CONSTRAINT DUTS_DUO_EVAPORATORS_uk_EVAPORATOR_ID UNIQUE KEY (EVAPORATOR_ID);
ALTER TABLE DUTS_DUO_EVAPORATORS ADD CONSTRAINT DUTS_DUO_EVAPORATORS_uk_DUT_DUO_ID UNIQUE KEY (DUT_DUO_ID);
ALTER TABLE DUTS_DUO_CONDENSERS ADD CONSTRAINT DUTS_DUO_CONDENSERS_uk_CONDENSER_ID UNIQUE KEY (CONDENSER_ID);
ALTER TABLE DUTS_DUO_CONDENSERS ADD CONSTRAINT DUTS_DUO_CONDENSERS_uk_DUT_DUO_ID UNIQUE KEY (DUT_DUO_ID);
ALTER TABLE DUTS_DUO_ASSET_HEAT_EXCHANGERS ADD CONSTRAINT DUTS_DUO_ASSET_HEAT_EXCHANGERS_uk_ASSET_HEAT_EXCHANGER_ID UNIQUE KEY (ASSET_HEAT_EXCHANGER_ID);
ALTER TABLE DUTS_DUO_ASSET_HEAT_EXCHANGERS ADD CONSTRAINT DUTS_DUO_ASSET_HEAT_EXCHANGERS_uk_DUT_DUO_ID UNIQUE KEY (DUT_DUO_ID);

-- $$ --

ALTER TABLE MACHINES_CURRENT_AUTOMATIONS_PARAMETERS
ADD CONSTRAINT MACHINE_ID UNIQUE (MACHINE_ID);
