CREATE TABLE CHILLER_CARRIER_30XA_HVAR_COMMANDS (
  ADDRESS int unsigned NOT NULL,
  R_W varchar(3) NOT NULL,
  ALIAS varchar(30) DEFAULT NULL,
  COMMAND varchar(20) NOT NULL,
  DESCRIPTION varchar(300) NOT NULL,
  DESCRIPTION_EN varchar(300) NOT NULL,
  FORMULA varchar(30) DEFAULT NULL,
  FUNC_ID tinyint unsigned NOT NULL,
  HAS_SIGNAL char(1) DEFAULT '1',
  ID tinyint unsigned NOT NULL DEFAULT 1,
  IP varchar(30) DEFAULT NULL,
  SIZE tinyint unsigned NOT NULL DEFAULT 1,
  SYS_ID tinyint unsigned NOT NULL DEFAULT 1,
  UNIT varchar(10) DEFAULT NULL,

  PRIMARY KEY (ADDRESS, R_W),
  CONSTRAINT CHILLER_CARRIER_30XA_HVAR_COMMANDS_uk_ALIAS UNIQUE KEY (ALIAS),
  CONSTRAINT CHILLER_CARRIER_30XA_HVAR_COMMANDS_uk_COMMAND UNIQUE KEY (COMMAND)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN0', 'GENUINT_UI', 'GENUNIT Update Interval',	'Intervalo de atualização da tabela GENUNIT', 's', 0, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN1', 'CTRL_TYP', 'Control Type', 'Tipo de controle', null, 1, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN2', 'STATUS', 'Run Status', 'Status do Chiller', null, 6, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN3', 'ALM', 'Alarm State', 'Estado do alarme', null, 11, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN4', 'SP_OCC', 'Setpoint Occupied?', 'Setpoint Ocupado?', null, 21, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN5', 'CHIL_S_S', 'CCN Chiller Start/Stop', 'Chiller Ligado / Desligado', null, 22, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN6', 'CHIL_OCC', 'Chiller Occupied?', 'Chiller ocupado?', null, 23, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN7', 'CAP_T', 'Percent Total Capacity', 'Percentual capacidade Total', '%', 24, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN8', 'DEM_LIM', 'Active Demand Limit Val', 'Limite de demanda ativado?', null, 25, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN9', 'TOT_CURR', 'Total current', 'Corrente total', 'A', 26, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN10', 'CTRL_PNT', 'Control Point', 'Ponto de controle (setpoint)', '°C', 29, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN11', 'OAT', 'External Temperature', 'Temperatura externa', '°C', 31, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN12', 'COOL_EWT', 'Cooler Entering Fluid Temp', 'Temperatura de entrada d''água evaporador', '°C', 33, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN13', 'COOL_LWT', 'Cooler Leaving Fluid Temp', 'Temperatura de saída d''água evaporador', '°C', 35, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN14', 'COND_EWT', 'Condenser Entering Fluid Temp', 'Temperatura de entrada d''água condensador', '°C', 37, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN15', 'COND_LWT', 'Condenser Leaving Fluid Temp', 'Temperatura de saída d''água condensador', '°C', 39, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN16', 'EMSTOP', 'Emergency Stop', 'Parada de emergência', null, 44, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN17', 'CIRCA_AN_UI', 'CIRCA_AN Update Interval', 'Intervalo de atualização da tabela CIRCA_AN', 's', 45, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN18', 'CAPA_T', 'Circuit A Percent Total Capacity', 'Percentual capacidade Total do circuito A', '%', 46, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN19', 'DP_A', 'Discharge Pressure', 'Pressão de descarga circuito A', 'kPa', 48, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN20', 'SP_A', 'Suction Pressure', 'Pressão de Sucção circuito A', 'kPa', 50, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN21', 'ECON_P_A', 'Economizer Pressure', 'Pressão do economizador do circuito A', 'kPa', 52, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN22', 'OP_A', 'Oil Pressure', 'Pressão de Óleo Compressor A', 'kPa', 54, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN23', 'DOP_A', 'Oil Pressure Delta', 'Delta de pressão do circuito A', 'kPa', 56, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN24', 'CURREN_A', 'Compressor Motor Temp', 'Corrente do Compressor do circuito A', 'A', 58, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN25', 'CP_TMP_A', 'Compressor Motor Current', 'Temperatura do Compressor do circuito A', '°C', 60, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN26', 'DGT_A', 'Discharge Temp', 'Temperatura de descarga do circuito A', '°C', 62, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN27', 'ECO_TP_A', 'Economizer Temp', 'Temperatura do economizador do circuito A', '°C', 64, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN28', 'SCT_A', 'Saturated Condensing Tmp', 'Temperatura saturada do Condensador circuito A', '°C', 66, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN29', 'SST_A', 'Saturated Suction Temp', 'Temperatura saturada do Sucção circuito A', '°C', 68, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN30', 'SUCT_T_A', 'Suction Temperature', 'Temperatura de sucção do circuito A', '°C', 70, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN31', 'EXV_A', 'EXV Position', 'Posição da válvula de expansão do circuito A', '%', 72, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN32', 'CIRCB_AN_UI', 'CIRCB_AN Update Interval', 'Intervalo de atualização da tabela CIRCB_AN', 's', 86, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN33', 'CAPB_T', 'Circuit B Percent Total Capacity', 'Percentual capacidade Total do circuito B', '%', 87, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN34', 'DP_B', 'Discharge Pressure', 'Pressão de descarga circuito B', 'kPa', 89, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN35', 'SP_B', 'Suction Pressure', 'Pressão de Sucção circuito B', 'kPa', 91, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN36', 'ECON_P_B', 'Economizer Pressure', 'Pressão do economizador do circuito B', 'kPa', 93, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN37', 'OP_B', 'Oil Pressure', 'Pressão de Óleo Compressor B', 'kPa', 95, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN38', 'DOP_B', 'Oil Pressure Delta', 'Delta de pressão do circuito B', 'kPa', 97, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN39', 'CURREN_B', 'Compressor Motor Current', 'Corrente do Compressor do circuito B', 'A', 99, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN40', 'CP_TMP_B', 'Compressor Motor Temp', 'Temperatura do Compressor do circuito B', '°C', 101, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN41', 'DGT_B', 'Discharge Temp', 'Temperatura de descarga do circuito B', '°C', 103, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN42', 'ECO_TP_B', 'Economizer Temp', 'Temperatura do economizador do circuito B', '°C', 105, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN43', 'SCT_B', 'Saturated Condensing Tmp', 'Temperatura saturada do Condensador circuito B', '°C', 107, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN44', 'SST_B', 'Saturated Suction Temp', 'Temperatura saturada do Sucção circuito B', '°C', 109, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN45', 'SUCT_T_B', 'Suction Temperature', 'Temperatura de sucção do circuito B', '°C', 111, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN46', 'EXV_B', 'EXV Position', 'Posição da válvula de expansão do circuito B', '%', 113, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN47', 'CIRCC_AN_UI', 'CIRCC_AN Update Interval', 'Intervalo de atualização da tabela CIRCC_AN', 's', 127, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN48', 'CAPC_T', 'Circuit C Percent Total Capacity', 'Percentual capacidade Total do circuito C', '%', 128, null, 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN49', 'DP_C', 'Discharge Pressure', 'Pressão de descarga circuito C', 'kPa', 130, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN50', 'SP_C', 'Suction Pressure', 'Pressão de Sucção circuito C', 'kPa', 132, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN51', 'ECON_P_C', 'Economizer Pressure', 'Pressão do economizador do circuito C', 'kPa', 134, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN52', 'OP_C', 'Oil Pressure', 'Pressão de Óleo Compressor C', 'kPa', 136, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN53', 'DOP_C', 'Oil Pressure Delta', 'Delta de pressão do circuito C', 'kPa', 138, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN54', 'CURREN_C', 'Compressor Motor Current', 'Corrente do Compressor do circuito C', 'A', 140, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN55', 'CP_TMP_C', 'Compressor Motor Temp', 'Temperatura do Compressor do circuito C', '°C', 142, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN56', 'DGT_C', 'Discharge Temp', 'Temperatura de descarga do circuito C', '°C', 144, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN57', 'ECO_TP_C', 'Economizer Temp', 'Temperatura do economizador do circuito C', '°C', 146, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN58', 'SCT_C', 'Saturated Condensing Tmp', 'Temperatura saturada do Condensador circuito C', '°C', 148, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN59', 'SST_C', 'Saturated Suction Temp', 'Temperatura saturada do Sucção circuito C', '°C', 150, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN60', 'SUCT_T_C', 'Suction Temperature', 'Temperatura de sucção do circuito C', '°C', 152, '/10', 3, 'R');
INSERT INTO CHILLER_CARRIER_30XA_HVAR_COMMANDS (COMMAND, ALIAS, DESCRIPTION_EN, DESCRIPTION, UNIT, ADDRESS, FORMULA, FUNC_ID, R_W) VALUES ('CMN61', 'EXV_C', 'EXV Position', 'Posição da válvula de expansão do circuito C', '%', 154, '/10', 3, 'R');

-- $$ --

UPDATE CHILLER_CARRIER_30XA_HVAR_COMMANDS SET ALIAS = 'GENUNIT_UI' WHERE ALIAS = 'GENUINT_UI';

DELETE FROM CHILLER_CARRIER_30XA_HVAR_COMMANDS WHERE ALIAS IN ('COND_EWT', 'COND_LWT');
