ALTER TABLE SENSORS ADD MULT_QUAD decimal(6, 4) DEFAULT 0 NOT NULL;
ALTER TABLE SENSORS ADD MULT_LIN decimal(6,4) NOT NULL DEFAULT MULT;
ALTER TABLE SENSORS ALTER MULT_LIN DROP DEFAULT;
ALTER TABLE SENSORS DROP MULT;