import * as AV_OPTS from './sql/AV_OPTS';
import * as CARRIER_ECOSPLIT_COMMANDS from './sql/CARRIER_ECOSPLIT_COMMANDS';
import * as CG_ET330_COMMANDS from './sql/CG_ET330_COMMANDS';
import * as CITY from './sql/CITY';
import * as CLIENTS from './sql/CLIENTS';
import * as CLUNITS from './sql/CLUNITS';
import * as DAMS from './sql/DAMS';
import * as DASHUSERS from './sql/DASHUSERS';
import * as DEVFWVERS from './sql/DEVFWVERS';
import * as DEVS from './sql/DEVS';
import * as DUTS from './sql/DUTS';
import * as ENERGY_MANUFACTURERS from './sql/ENERGY_MANUFACTURERS';
import * as ENERGY_METER_MODELS from './sql/ENERGY_METER_MODELS';
import * as PWRECOVERTK from './sql/PWRECOVERTK';
import * as NOTIFDESTS from './sql/NOTIFDESTS';
import * as NOTIFSCFG from './sql/NOTIFSCFG';
import * as ROOMTYPES from './sql/ROOMTYPES';
import * as SENSORS from './sql/SENSORS';
import * as STATEREGION from './sql/STATEREGION';
import * as USERSCLIENTS from './sql/USERSCLIENTS';
import * as SIMCARDS from './sql/SIMCARDS';
import * as FERIADOS from './sql/FERIADOS';
import * as FIRMWARES from './sql/FIRMWARES';
import * as AUTOM_EVAP from './sql/AUTOM_EVAP';
import * as USERSTOKENS from './sql/USERSTOKENS';
import * as MANUFACT_DEVS from './sql/MANUFACT_DEVS';
import * as ECOCMDHIST from './sql/ECOCMDHIST';
import * as cache_cond_tel from './sql/cache_cond_tel';
import * as DRIS from './sql/DRIS';
import * as DRISCHEDS from './sql/DRISCHEDS';
import * as INTEGRNESS from './sql/INTEGRNESS';
import * as INTEGROXYN from './sql/INTEGROXYN';
import * as INTEGRCOOLAUT from './sql/INTEGRCOOLAUT';
import * as ROOMS from './sql/ROOMS';
import * as cache_gameter_cons from './sql/cache_gameter_cons';
import * as VISITATECNICA from './sql/VISITATECNICA';
import * as VTENVIRONMENTS from './sql/VTENVIRONMENTS';
import * as VTMACHINES from './sql/VTMACHINES';
import * as VTENVIMAGES from './sql/VTENVIMAGES';
import * as VTMACHINEIMAGES from './sql/VTMACHINEIMAGES';
import * as VTMACHINEMACHINES from './sql/VTMACHINEMACHINES';
import * as VTMACHINEENVS from './sql/VTMACHINEENVS';
import * as VTMACHINEENVSLOCATION from './sql/VTMACHINEENVSLOCATION';
import * as VTENERGIES from './sql/VTENERGIES';
import * as VTENERGYIMAGES from './sql/VTENERGYIMAGES';
import * as VTWATERMEASURERS from './sql/VTWATERMEASURERS';
import * as VTWATERMEASURERIMAGES from './sql/VTWATERMEASURERIMAGES';
import * as VTDRTS from './sql/VTDRTS';
import * as VTDRTIMAGES from './sql/VTDRTIMAGES';
import * as VTRACKS from './sql/VTRACKS';
import * as VTRACKIMAGES from './sql/VTRACKIMAGES';
import * as VTACCESSPOINTS from './sql/VTACCESSPOINTS';
import * as VTACCESSPOINTIMAGES from './sql/VTACCESSPOINTIMAGES';
import * as VTSERVEDENVIRONMENTMACHINE from './sql/VTSERVEDENVIRONMENTMACHINE';
import * as UNITSUPERVISORS from './sql/UNITSUPERVISORS';
import * as UNITCLASSES from './sql/UNITCLASSES';
import * as CLASSES from './sql/CLASSES';
import * as ASSOCIATIONS from './sql/ASSOCIATIONS';
import * as ACCESS_DISTRIBUTORS from './sql/ACCESS_DISTRIBUTORS';
import * as DISTRIBUTORS from './sql/DISTRIBUTORS';
import * as BASELINE_TEMPLATES from './sql/BASELINE_TEMPLATES';
import * as BASELINES from './sql/BASELINES';
import * as BASELINE_VALUES from './sql/BASELINE_VALUES';
import * as VTMACHINETYPES from './sql/VTMACHINETYPES';
import * as INVOICES from './sql/INVOICES';
import * as DUTS_SPOTS_HISTORY from './sql/DUTS_SPOTS_HISTORY';
import * as AUTOM_GROUPS_HISTORY from './sql/AUTOM_GROUPS_HISTORY';
import * as NEXUS_II_COMMANDS from './sql/NEXUS_II_COMMANDS';
import * as ETE_30_COMMANDS from './sql/ETE_30_COMMANDS';
import * as CONFIGS from './sql/CONFIGS';
import * as MSGTOSERVICE from './sql/MSGTOSERVICE';
import * as CG_EM210_COMMANDS from './sql/CG_EM210_COMMANDS';
import * as DUTS_SCHEDULES from './sql/DUTS_SCHEDULES';
import * as DUTS_EXCEPTIONS from './sql/DUTS_EXCEPTIONS';
import * as HEAT_EXCHANGERS from './sql/HEAT_EXCHANGERS';
import * as VAV_BAC_COMMANDS from './sql/VAV_BAC_COMMANDS';
import * as VAVS from './sql/VAVS';
import * as FANCOILS from './sql/FANCOILS';
import * as KRON_MULTK_COMMANDS from './sql/KRON_MULTK_COMMANDS';
import * as DUTS_PERIODS from './sql/SETPOINTS_PERIODS';
import * as DUTS_PERIODS_SETTINGS from './sql/SETPOINTS_PERIODS_SETTINGS';
import * as TIME_ZONES from './sql/TIME_ZONES';
import * as COUNTRY from './sql/COUNTRY';
import * as UNITS_SKETCHES from './sql/UNITS_SKETCHES';
import * as KRON_IKRON_03_COMMANDS from './sql/KRON_IKRON_03_COMMANDS';
import * as SCHNEIDER_PM2100_COMMANDS from './sql/SCHNEIDER_PM2100_COMMANDS';
import * as EMAILSEND from './sql/EMAILSEND';
import * as cache_unit_autom_savings from './sql/cache_unit_autom_savings';
import * as NOBREAKS from './sql/NOBREAKS';
import * as DMTS from './sql/DMTS';
import * as DMTS_NOBREAKS from './sql/DMTS_NOBREAKS';
import * as ASSETS from './sql/ASSETS';
import * as ASSET_IMAGES from './sql/ASSET_IMAGES';
import * as DMT_IMAGES from './sql/DMT_IMAGES';
import * as DEVICES from './sql/DEVICES';
import * as DEVICES_CLIENTS from './sql/DEVICES_CLIENTS';
import * as DEVICES_UNITS from './sql/DEVICES_UNITS';
import * as NOBREAK_IMAGES from './sql/NOBREAK_IMAGES';
import * as DALS from './sql/DALS';
import * as DALS_ILLUMINATIONS from './sql/DALS_ILLUMINATIONS';
import * as ILLUMINATIONS from './sql/ILLUMINATIONS';
import * as DAM_SCHEDULES from './sql/DAM_SCHEDULES';
import * as NOTIF_SCHEDULE from './sql/NOTIFSCHEDULE';
import * as ENVIRONMENTS from './sql/ENVIRONMENTS';
import * as DUTS_DEVICES_ROOMS from './sql/DUTS_DEVICES_ROOMS';
import * as ENVIRONMENTS_ROOM_TYPES from './sql/ENVIRONMENTS_ROOM_TYPES';
import * as REFRIGERATES from './sql/REFRIGERATES';
import * as DUTS_DEVICES from './sql/DUTS_DEVICES';
import * as DUTS_MONITORING from './sql/DUTS_MONITORING';
import * as DUTS_AUTOMATION from './sql/DUTS_AUTOMATION';
import * as DUTS_DUO from './sql/DUTS_DUO';
import * as DUTS_DUO_ASSET_HEAT_EXCHANGERS from './sql/DUTS_DUO_ASSET_HEAT_EXCHANGERS';
import * as DUTS_DUO_EVAPORATORS from './sql/DUTS_DUO_EVAPORATORS';
import * as DUTS_DUO_CONDENSERS from './sql/DUTS_DUO_CONDENSERS';
import * as DUTS_DUO_AIR_CURTAINS from './sql/DUTS_DUO_AIR_CURTAINS';
import * as DUTS_REFERENCE from './sql/DUTS_REFERENCE';
import * as DUTS_DEVICES_IMAGES from './sql/DUTS_DEVICES_IMAGES';
import * as AUTOMATIONS_PERIODS from './sql/AUTOMATIONS_PERIODS';
import * as MACHINES_AUTOMATIONS_PERIODS from './sql/MACHINES_AUTOMATIONS_PERIODS';
import * as AUTOMATIONS_PARAMETERS from './sql/AUTOMATIONS_PARAMETERS';
import * as AUTOMATIONS_PERIODS_PARAMETERS from './sql/AUTOMATIONS_PERIODS_PARAMETERS';
import * as SCHEDULES from './sql/SCHEDULES';
import * as EXCEPTIONS from './sql/EXCEPTIONS';
import * as SETPOINTS_PERIODS from './sql/SETPOINTS_PERIODS';
import * as SETPOINTS_PERIODS_SETTINGS from './sql/SETPOINTS_PERIODS_SETTINGS';
import * as CURRENT_AUTOMATIONS_PARAMETERS from './sql/CURRENT_AUTOMATIONS_PARAMETERS';
import * as MACHINES_CURRENT_AUTOMATIONS_PARAMETERS from './sql/MACHINES_CURRENT_AUTOMATIONS_PARAMETERS';
import * as DAMS_DEVICES from './sql/DAMS_DEVICES';
import * as DAMS_AUTOMATIONS from './sql/DAMS_AUTOMATIONS';
import * as DACS_AUTOMATIONS from './sql/DACS_AUTOMATIONS';
import * as DRIS_DEVICES from './sql/DRIS_DEVICES';
import * as DRIS_AUTOMATIONS from './sql/DRIS_AUTOMATIONS';
import * as DAMS_DEVICES_IMAGES from './sql/DAMS_DEVICES_IMAGES';
import * as DRIS_DEVICES_IMAGES from './sql/DRIS_DEVICES_IMAGES';
import * as DAMS_ILLUMINATIONS from './sql/DAMS_ILLUMINATIONS';
import * as HYDROMETER_MODELS from './sql/HYDROMETER_MODELS';
import * as WATERS from './sql/WATERS';
import * as LEAK_ANALYSIS from './sql/LEAK_ANALYSIS';
import * as DMAS_DEVICES from './sql/DMAS_DEVICES';
import * as DMAS_IMAGES from './sql/DMAS_IMAGES';
import * as DMAS_HIST from './sql/DMAS_HIST';
import * as LAAGER from './sql/LAAGER';
import * as LAAGER_IMAGES from './sql/LAAGER_IMAGES';
import * as LAAGER_HIST from './sql/LAAGER_HIST';
import * as LAAGER_HISTORY_USAGE from './sql/LAAGER_HISTORY_USAGE';
import * as LAAGER_DAILY_HISTORY_USAGE from './sql/LAAGER_DAILY_HISTORY_USAGE';
import * as CURRENT_WATERS_CONSUMPTION from './sql/CURRENT_WATERS_CONSUMPTION';
import * as CURRENT_DMAS_CONSUMPTION from './sql/CURRENT_DMAS_CONSUMPTION';
import * as CURRENT_LAAGER_CONSUMPTION from './sql/CURRENT_LAAGER_CONSUMPTION';
import * as MACHINES_SETPOINTS_AUTOMATION_HIST from './sql/MACHINES_SETPOINTS_AUTOMATION_HIST';
import * as MACHINES from './sql/MACHINES';
import * as ASSOC_MACHINES from './sql/ASSOC_MACHINES';
import * as MACHINE_IMAGES from './sql/MACHINE_IMAGES';
import * as DACS_DEVICES from './sql/DACS_DEVICES';
import * as AIR_CURTAINS from './sql/AIR_CURTAINS';
import * as CONDENSERS from './sql/CONDENSERS';
import * as EVAPORATORS from './sql/EVAPORATORS';
import * as ASSETS_HEALTH  from './sql/ASSETS_HEALTH';
import * as ASSETS_HEALTH_HIST from './sql/ASSETS_HEALTH_HIST';
import * as DAC_IMAGES from './sql/DAC_IMAGES';
import * as FAULTS_DATAS from './sql/FAULTS_DATAS';
import * as HEALTH_BEFORE_OFFLINE from './sql/HEALTH_BEFORE_OFFLINE';
import * as L1_SOURCE from './sql/L1_SOURCE';
import * as DACS_CONDENSERS from './sql/DACS_CONDENSERS';
import * as ASSETS_HEALTH_OBS from './sql/ASSETS_HEALTH_OBS';
import * as DACS_EVAPORATORS from './sql/DACS_EVAPORATORS';
import * as P_CAUSES from './sql/P_CAUSES';
import * as DMTS_NOBREAK_CIRCUITS from './sql/DMTS_NOBREAK_CIRCUITS';
import * as RATE_MODELS from './sql/RATE_MODELS';
import * as WHITERATE_PARAMETERS from './sql/WHITERATE_PARAMETERS';
import * as CONVENTIONALRATE_PARAMETERS from './sql/CONVENTIONAL_PARAMETERS';
import * as RATE_CICLES from './sql/RATE_CICLES';
import * as RATE_MODALITY from './sql/RATE_MODALITY';
import * as RATE_GROUPS from './sql/RATE_GROUPS';
import * as RATE_SUBGROUPS from './sql/RATE_SUBGROUPS';
import * as DMTS_ILLUMINATIONS from './sql/DMTS_ILLUMINATIONS';
import * as DAL_IMAGES from './sql/DAL_IMAGES';
import * as ILLUMINATION_IMAGES from './sql/ILLUMINATION_IMAGES';
import * as DALS_SCHEDULES from './sql/DALS_SCHEDULES';
import * as DALS_EXCEPTIONS from './sql/DALS_EXCEPTIONS';
import * as EVAPORATORS_HEAT_EXCHANGERS from './sql/EVAPORATORS_HEAT_EXCHANGERS';
import * as CONDENSERS_HEAT_EXCHANGERS from './sql/CONDENSERS_HEAT_EXCHANGERS';
import * as ENERGY_DEVICES_INFO from './sql/ENERGY_DEVICES_INFO';
import * as DRIS_ENERGY_DEVICES from './sql/DRIS_ENERGY_DEVICES';
import * as DRIS_ENERGY_DEVICES_HIST from './sql/DRIS_ENERGY_DEVICES_HIST';
import * as GREENANT_ENERGY_DEVICES from './sql/GREENANT_ENERGY_DEVICES';
import * as ELECTRIC_CIRCUITS from './sql/ELECTRIC_CIRCUITS';
import * as ELECTRIC_CIRCUITS_ILLUMINATIONS from './sql/ELECTRIC_CIRCUITS_ILLUMINATIONS';
import * as ELECTRIC_CIRCUITS_MACHINES from './sql/ELECTRIC_CIRCUITS_MACHINES';
import * as ELECTRIC_CIRCUITS_NOBREAKS from './sql/ELECTRIC_CIRCUITS_NOBREAKS';
import * as ELECTRIC_CIRCUITS_TREE from './sql/ELECTRIC_CIRCUITS_TREE';
import * as ADDITIONAL_MACHINE_PARAMETERS from './sql/ADDITIONAL_MACHINE_PARAMETERS';
import * as ADDITIONAL_NOBREAK_PARAMETERS from './sql/ADDITIONAL_NOBREAK_PARAMETERS';
import * as EVAPORATORS_MODELS from './sql/EVAPORATORS_MODELS';
import * as ASSET_HEAT_EXCHANGERS from './sql/ASSET_HEAT_EXCHANGERS';
import * as DACS_ASSET_HEAT_EXCHANGERS from './sql/DACS_ASSET_HEAT_EXCHANGERS';
import * as ILLUMINATIONS_CURRENT_AUTOMATIONS_PARAMETERS from './sql/ILLUMINATIONS_CURRENT_AUTOMATIONS_PARAMETERS';
import * as SIMCARDS_IMAGES from  './sql/SIMCARDS_IMAGES';
import * as IR_CODES from './sql/IR_CODES';
import * as OBSERVATIONS from './sql/OBSERVATIONS';
import * as UNITS_OBSERVATIONS from './sql/UNITS_OBSERVATIONS';
import * as DUTS_IR_CODES from './sql/DUTS_IR_CODES';
import * as PREFS_OVERVIEW from './sql/PREFS_OVERVIEW';
import * as PREFS_OVERVIEW_INFO from './sql/PREFS_OVERVIEW_INFO';
import * as GROUND_PLANS from './sql/GROUND_PLANS';
import * as GROUND_PLANS_UNITS from './sql/GROUND_PLANS_UNITS';
import * as DEV_POINTS from './sql/DEV_POINTS';
import * as GROUND_PLANS_POINTS from './sql/GROUND_PLANS_POINTS';
import * as WATERS_MONTH_HISTORY_USAGE from './sql/WATERS_MONTH_HISTORY_USAGE';
import * as CHILLER_CARRIER_30HXE_GXE_COMMANDS from './sql/CHILLER_CARRIER_30HXE_GXE_COMMANDS';
import * as DRIS_ASSET_HEAT_EXCHANGERS from './sql/DRIS_ASSET_HEAT_EXCHANGERS';
import * as CHILLER_CARRIER_ALARMS from './sql/CHILLER_CARRIER_ALARMS';
import * as DRIS_CHILLER_ALARMS_HIST from './sql/DRIS_CHILLER_ALARMS_HIST';
import * as ANALYSIS_MODELS from './sql/ANALYSIS_MODELS';
import * as CHILLERS from './sql/CHILLERS';
import * as CHILLER_CARRIER_MODELS from './sql/CHILLER_CARRIER_MODELS';
import * as DRIS_CHILLERS from './sql/DRIS_CHILLERS';
import * as CURRENT_DEVICE_STATE from './sql/CURRENT_DEVICE_STATE';
import * as KRON_MULTK_120_COMMANDS from './sql/KRON_MULTK_120_COMMANDS'
import * as CHILLER_CARRIER_30XA_XW_XS_XV_COMMANDS from './sql/CHILLER_CARRIER_30XA_XW_XS_XV_COMMANDS';
import * as CHILLER_CARRIER_30XA_HVAR_COMMANDS from './sql/CHILLER_CARRIER_30XA_HVAR_COMMANDS';
import * as CHILLER_CARRIER_LINES from './sql/CHILLER_CARRIER_LINES';
import * as SCHNEIDER_PM210_COMMANDS from './sql/SCHNEIDER_PM210_COMMANDS';
import * as VAV_BAC_6000_AMLN_COMMANDS from './sql/VAV_BAC_6000_AMLN_COMMANDS';
import * as SENSOR_FIRMWARE_CURVES from './sql/SENSOR_FIRMWARE_CURVES';
import * as CARRIER_ECOSPLIT_AUTOMATION_COMMANDS from './sql/CARRIER_ECOSPLIT_AUTOMATION_COMMANDS';
import * as VAV_BAC_AUTOMATION_COMMANDS from './sql/VAV_BAC_AUTOMATION_COMMANDS';
import * as VAV_BAC_6000_AMLN_AUTOMATION_COMMANDS from './sql/VAV_BAC_6000_AMLN_AUTOMATION_COMMANDS';
import * as SCHNEIDER_PM9C_COMMANDS from './sql/SCHNEIDER_PM9C_COMMANDS';

export default {
  RATE_MODELS,
  RATE_MODALITY,
  RATE_SUBGROUPS,
  RATE_GROUPS,
  RATE_CICLES,
  CONVENTIONALRATE_PARAMETERS,
  WHITERATE_PARAMETERS,
  NOBREAK_IMAGES,
  AV_OPTS,
  CARRIER_ECOSPLIT_COMMANDS,
  CG_ET330_COMMANDS,
  CITY,
  CLIENTS,
  CLUNITS,
  DAMS,
  DASHUSERS,
  DEVFWVERS,
  DEVS,
  DUTS,
  ENERGY_MANUFACTURERS,
  ENERGY_METER_MODELS,
  PWRECOVERTK,
  NOTIFDESTS,
  NOTIFSCFG,
  ROOMTYPES,
  SENSORS,
  STATEREGION,
  USERSCLIENTS,
  SIMCARDS,
  FERIADOS,
  FIRMWARES,
  AUTOM_EVAP,
  USERSTOKENS,
  MANUFACT_DEVS,
  ECOCMDHIST,
  cache_cond_tel,
  DRIS,
  DRISCHEDS,
  INTEGRNESS,
  INTEGROXYN,
  INTEGRCOOLAUT,
  ROOMS,
  cache_gameter_cons,
  VISITATECNICA,
  VTENVIRONMENTS,
  VTMACHINES,
  VTENVIMAGES,
  VTMACHINEIMAGES,
  VTMACHINEMACHINES,
  VTMACHINEENVS,
  VTMACHINEENVSLOCATION,
  UNITSUPERVISORS,
  UNITCLASSES,
  CLASSES,
  ASSOCIATIONS,
  VTENERGIES,
  VTENERGYIMAGES,
  VTWATERMEASURERS,
  VTWATERMEASURERIMAGES,
  VTDRTS,
  VTDRTIMAGES,
  VTRACKS,
  VTRACKIMAGES,
  VTACCESSPOINTS,
  VTACCESSPOINTIMAGES,
  VTSERVEDENVIRONMENTMACHINE,
  ACCESS_DISTRIBUTORS,
  DISTRIBUTORS,
  BASELINE_TEMPLATES,
  BASELINES,
  BASELINE_VALUES,
  VTMACHINETYPES,
  INVOICES,
  DUTS_SPOTS_HISTORY,
  AUTOM_GROUPS_HISTORY,
  CONFIGS,
  DUTS_SCHEDULES,
  DUTS_EXCEPTIONS,
  NEXUS_II_COMMANDS,
  ETE_30_COMMANDS,
  MSGTOSERVICE,
  HEAT_EXCHANGERS,
  CG_EM210_COMMANDS,
  VAV_BAC_COMMANDS,
  VAVS,
  FANCOILS,
  KRON_MULTK_COMMANDS,
  DUTS_PERIODS,
  DUTS_PERIODS_SETTINGS,
  TIME_ZONES,
  COUNTRY,
  UNITS_SKETCHES,
  KRON_IKRON_03_COMMANDS,
  SCHNEIDER_PM2100_COMMANDS,
  EMAILSEND,
  cache_unit_autom_savings,
  DMTS,
  DMTS_NOBREAKS,
  DMT_IMAGES,
  NOBREAKS,
  ASSETS,
  ASSET_IMAGES,
  DEVICES,
  DEVICES_UNITS,
  DEVICES_CLIENTS,
  DALS,
  DALS_ILLUMINATIONS,
  ILLUMINATIONS,
  DAM_SCHEDULES,
  NOTIF_SCHEDULE,
  ENVIRONMENTS,
  DUTS_DEVICES_ROOMS,
  ENVIRONMENTS_ROOM_TYPES,
  REFRIGERATES,
  DUTS_DEVICES,
  DUTS_AUTOMATION,
  DUTS_MONITORING,
  DUTS_DUO,
  DUTS_DUO_ASSET_HEAT_EXCHANGERS,
  DUTS_DUO_EVAPORATORS,
  DUTS_DUO_CONDENSERS,
  DUTS_DUO_AIR_CURTAINS,
  DUTS_REFERENCE,
  DUTS_DEVICES_IMAGES,
  AUTOMATIONS_PERIODS,
  MACHINES_AUTOMATIONS_PERIODS,
  AUTOMATIONS_PARAMETERS,
  AUTOMATIONS_PERIODS_PARAMETERS,
  SCHEDULES,
  EXCEPTIONS,
  SETPOINTS_PERIODS,
  SETPOINTS_PERIODS_SETTINGS,
  CURRENT_AUTOMATIONS_PARAMETERS,
  MACHINES_CURRENT_AUTOMATIONS_PARAMETERS,
  DAMS_DEVICES,
  DAMS_AUTOMATIONS,
  DACS_AUTOMATIONS,
  DRIS_DEVICES,
  DRIS_AUTOMATIONS,
  DAMS_DEVICES_IMAGES,
  DRIS_DEVICES_IMAGES,
  DAMS_ILLUMINATIONS,
  HYDROMETER_MODELS,
  WATERS,
  LEAK_ANALYSIS,
  DMAS_DEVICES,
  DMAS_IMAGES,
  DMAS_HIST,
  LAAGER,
  LAAGER_IMAGES,
  LAAGER_HIST,
  LAAGER_HISTORY_USAGE,
  LAAGER_DAILY_HISTORY_USAGE,
  CURRENT_WATERS_CONSUMPTION,
  CURRENT_DMAS_CONSUMPTION,
  CURRENT_LAAGER_CONSUMPTION,
  MACHINES_SETPOINTS_AUTOMATION_HIST,
  MACHINES,
  ASSOC_MACHINES,
  MACHINE_IMAGES,
  DACS_DEVICES,
  AIR_CURTAINS,
  CONDENSERS,
  EVAPORATORS,
  ASSETS_HEALTH,
  ASSETS_HEALTH_HIST,
  DAC_IMAGES,
  FAULTS_DATAS,
  HEALTH_BEFORE_OFFLINE,
  L1_SOURCE,
  DACS_CONDENSERS,
  ASSETS_HEALTH_OBS,
  DACS_EVAPORATORS,
  P_CAUSES,
  DMTS_NOBREAK_CIRCUITS,
  DAL_IMAGES,
  ILLUMINATION_IMAGES,
  DALS_SCHEDULES,
  DALS_EXCEPTIONS,
  DMTS_ILLUMINATIONS,
  EVAPORATORS_HEAT_EXCHANGERS,
  CONDENSERS_HEAT_EXCHANGERS,
  ENERGY_DEVICES_INFO,
  DRIS_ENERGY_DEVICES,
  DRIS_ENERGY_DEVICES_HIST,
  GREENANT_ENERGY_DEVICES,
  ELECTRIC_CIRCUITS,
  ELECTRIC_CIRCUITS_ILLUMINATIONS,
  ELECTRIC_CIRCUITS_MACHINES,
  ELECTRIC_CIRCUITS_NOBREAKS,
  ELECTRIC_CIRCUITS_TREE,
  ADDITIONAL_MACHINE_PARAMETERS,
  ADDITIONAL_NOBREAK_PARAMETERS,
  EVAPORATORS_MODELS,
  ASSET_HEAT_EXCHANGERS,
  DACS_ASSET_HEAT_EXCHANGERS,
  ILLUMINATIONS_CURRENT_AUTOMATIONS_PARAMETERS,
  SIMCARDS_IMAGES,
  IR_CODES,
  DUTS_IR_CODES,
  PREFS_OVERVIEW,
  PREFS_OVERVIEW_INFO,
  OBSERVATIONS,
  UNITS_OBSERVATIONS,
  GROUND_PLANS,
  GROUND_PLANS_POINTS,
  GROUND_PLANS_UNITS,
  DEV_POINTS,
  WATERS_MONTH_HISTORY_USAGE,
  CHILLER_CARRIER_30HXE_GXE_COMMANDS,
  DRIS_ASSET_HEAT_EXCHANGERS,
  CHILLER_CARRIER_ALARMS,
  DRIS_CHILLER_ALARMS_HIST,
  ANALYSIS_MODELS,
  CHILLERS,
  CHILLER_CARRIER_MODELS,
  DRIS_CHILLERS,
  CURRENT_DEVICE_STATE,
  KRON_MULTK_120_COMMANDS,
  CHILLER_CARRIER_30XA_XW_XS_XV_COMMANDS,
  CHILLER_CARRIER_LINES,
  SCHNEIDER_PM210_COMMANDS,
  VAV_BAC_6000_AMLN_COMMANDS,
  SENSOR_FIRMWARE_CURVES,
  CHILLER_CARRIER_30XA_HVAR_COMMANDS,
  CARRIER_ECOSPLIT_AUTOMATION_COMMANDS,
  VAV_BAC_6000_AMLN_AUTOMATION_COMMANDS,
  VAV_BAC_AUTOMATION_COMMANDS,
  SCHNEIDER_PM9C_COMMANDS,
}
