# .github/workflows/build-and-update-manifest.yaml
name: Build and Update Manifest

on:
  push:
    branches:
      - main  # Execute ao fazer push na branch principal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use Google Cloud Registry
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: "v${{ github.run_number }}"  # Define a tag única para cada build
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          cp configfile_example.ts configfile.ts
          cp serviceApiAsync/configfile_example.ts serviceApiAsync/configfile.ts
          cp serviceAuth/configfile_example.ts serviceAuth/configfile.ts
          cp serviceBGTasks/configfile_example.ts serviceBGTasks/configfile.ts
          cp serviceGateway/configfile_example.ts serviceGateway/configfile.ts
          cp serviceHealth/configfile_example.ts serviceHealth/configfile.ts
          cp serviceInvoice/configfile_example.ts serviceInvoice/configfile.ts
          cp serviceRealtime/configfile_example.ts serviceRealtime/configfile.ts
          cp serviceSWDocs/configfile_example.ts serviceSWDocs/configfile.ts
          cp serviceTelegram/configfile_example.ts serviceTelegram/configfile.ts
          docker build -t gcr.io/$GCP_PROJECT_ID/apiasync-teste:${IMAGE_TAG} -f Dockerfile.apiasync .
          docker push gcr.io/$GCP_PROJECT_ID/apiasync-teste:${IMAGE_TAG}
          docker image rm  gcr.io/$GCP_PROJECT_ID/apiasync-teste:${IMAGE_TAG}
          docker build -t gcr.io/$GCP_PROJECT_ID/auth-teste:${IMAGE_TAG} -f Dockerfile.auth .
          docker push gcr.io/$GCP_PROJECT_ID/auth-teste:${IMAGE_TAG}
          docker image rm  gcr.io/$GCP_PROJECT_ID/auth-teste:${IMAGE_TAG}
          docker build -t gcr.io/$GCP_PROJECT_ID/bgtasks-teste:${IMAGE_TAG} -f Dockerfile.bgtasks .
          docker push gcr.io/$GCP_PROJECT_ID/bgtasks-teste:${IMAGE_TAG}
          docker image rm  gcr.io/$GCP_PROJECT_ID/bgtasks-teste:${IMAGE_TAG}
          docker build -t gcr.io/$GCP_PROJECT_ID/health-teste:${IMAGE_TAG} -f Dockerfile.health .
          docker push gcr.io/$GCP_PROJECT_ID/health-teste:${IMAGE_TAG}
          docker image rm  gcr.io/$GCP_PROJECT_ID/health-teste:${IMAGE_TAG}
          docker build -t gcr.io/$GCP_PROJECT_ID/realtime-teste:${IMAGE_TAG} -f Dockerfile.realtime .
          docker push gcr.io/$GCP_PROJECT_ID/realtime-teste:${IMAGE_TAG}
          docker image rm  gcr.io/$GCP_PROJECT_ID/realtime-teste:${IMAGE_TAG}

      - name: Checkout Manifest Repository
        uses: actions/checkout@v2
        with: 
          repository: dielenergia/manifests-kubernetes # Nome do repositório de manifestos
          token: ${{ secrets.GIT_TOKEN }}
          path: manifest-repo

      - name: List Manifest Repository Files
        run: ls -R manifest-repo

      - name: Check Git Status
        working-directory: manifest-repo
        run: git status

      - name: Update Deployment Manifest
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE_TAG: "v${{ github.run_number }}"
        run: |
          sed -i "s|image: gcr.io/.*/apiasync.*|image: gcr.io/$GCP_PROJECT_ID/apiasync-teste:${IMAGE_TAG}|g" manifest-repo/apiserver/apiasync-deployment.yaml
          sed -i "s|image: gcr.io/.*/auth.*|image: gcr.io/$GCP_PROJECT_ID/auth-teste:${IMAGE_TAG}|g" manifest-repo/apiserver/auth-deployment.yaml
          sed -i "s|image: gcr.io/.*/bgtasks.*|image: gcr.io/$GCP_PROJECT_ID/bgtasks-teste:${IMAGE_TAG}|g" manifest-repo/apiserver/bgtasks-deployment.yaml
          sed -i "s|image: gcr.io/.*/health.*|image: gcr.io/$GCP_PROJECT_ID/health-teste:${IMAGE_TAG}|g" manifest-repo/apiserver/health-deployment.yaml
          sed -i "s|image: gcr.io/.*/realtime.*|image: gcr.io/$GCP_PROJECT_ID/realtime-teste:${IMAGE_TAG}|g" manifest-repo/apiserver/realtime-deployment.yaml

      - name: Commit and Push Manifest Update
        working-directory: manifest-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Atualiza a imagem para a versão $IMAGE_TAG"
          git push
